--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/android:api-26-alpha"
    environment: 
      JVM_OPTS: "-Xmx3200m"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
      - 
        run: 
          command: "./gradlew androidDependencies"
          name: "Download Dependencies"
      - 
        save_cache: 
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: 
          command: "sdkmanager \"system-images;android-27;default;armeabi-v7a\" && echo \"no\" | avdmanager create avd -n test -k \"system-images;android-16;default;armeabi-v7a\""
          name: "Setup emulator"
      - 
        run: 
          background: true
          command: "export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose"
          name: "Launch emulator"
      - 
        run: 
          command: |
              # wait for it to have booted
              circle-android wait-for-boot
              # unlock the emulator screen
              sleep 30
              adb shell input keyevent 82
          name: "Wait emulator"
      - 
        run: 
          command: "./gradlew connectedAndroidTest"
          name: "Run EspressoTests"
      - 
        store_artifacts: 
          destination: reports
          path: app/build/reports
      - 
        store_test_results: 
          path: app/build/test-results
    working_directory: ~/code
version: 2
